schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bndr/gojenkins"]
    version = "v1.0.1"
    hash = "sha256-H43dVsPhDdQVnMXMfVtr5LhWo1BokTEHM/fGtYEn0JQ="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/docker/distribution"]
    version = "v2.8.1+incompatible"
    hash = "sha256-xB+w8Uaz8T6jb2LOJU5XAoMHFg/YQd3MfDFOUNKlMxE="
  [mod."github.com/emersion/go-sasl"]
    version = "v0.0.0-20200509203442-7bfe0ed36a21"
    hash = "sha256-EAeSHTKDYNg223TdH+SM4Hz+N5R2HxHDyInxyObWUHk="
  [mod."github.com/emersion/go-smtp"]
    version = "v0.16.0"
    hash = "sha256-LAgQf5+KxyzgsiXHDUlBVA5Y470nVWHQqLlSdbY87t0="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.9.0"
    hash = "sha256-qt0M3tryKAzQS4JbmTr/N5+47Ue63U0dpbWov2Me5Os="
  [mod."github.com/evanphx/json-patch"]
    version = "v4.12.0+incompatible"
    hash = "sha256-rUOokb3XW30ftpHp0fsF2WiJln1S0FSt2El7fTHq3CM="
  [mod."github.com/evanphx/json-patch/v5"]
    version = "v5.6.0"
    hash = "sha256-9P31eky/JuDLlVmKUk4+SfoXWLuJqANm5gSMDzR82No="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/go-chi/chi"]
    version = "v4.0.0+incompatible"
    hash = "sha256-wRaYecq/359G5ebFkwsprfdj3tcc5y44CBbMBdvpXek="
  [mod."github.com/go-errors/errors"]
    version = "v1.0.1"
    hash = "sha256-lwqRiu2aeEvoSATSZO5X8hrBRNG4mUhPnj2nMO289mc="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/zapr"]
    version = "v1.2.3"
    hash = "sha256-bnUFAqMcSw2Tp0kjmOjq9MNvfVAmt/cFU7KYtTHCHeM="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.0"
    hash = "sha256-I9LAFczrUZC5MIznr/SqY0RdnQFEkAp1MJbz7h1EnGk="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.14"
    hash = "sha256-MRuOz461M5BHBAGYJdhBA8vP682EocgvgGQxpXxhJbo="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/btree"]
    version = "v1.0.1"
    hash = "sha256-1PIeFGgUL4BK/StL/D12pg9bEQ5HfMT/fMLdus4pZTs="
  [mod."github.com/google/gnostic"]
    version = "v0.5.7-v3refs"
    hash = "sha256-faR3RiaCBLgZsG1H5KRimlyOu4Grv1ENlYn3f7OAzhU="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/gofuzz"]
    version = "v1.1.0"
    hash = "sha256-PSNufXo20YXfSNbayCc3hdujKZT5EW4lybsQ+WJ0Imo="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/google/uuid"]
    version = "v1.1.2"
    hash = "sha256-DXttjObhEiMn5/OH+mYkJU6u03Gwsx5t08lTsIFyd+U="
  [mod."github.com/gregjones/httpcache"]
    version = "v0.0.0-20180305231024-9cad4c3443a7"
    hash = "sha256-2ngFfFuSm8YSTNZWGQuN5yTpsXlwY2R8aaIzjDnjTXI="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.6"
    hash = "sha256-B4uSmAVWme2nDAqbW9XiwlEnCg7CAvewToNsji7yf9E="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.1"
    hash = "sha256-ZTP9pLgwAAvHYK5A4PqwWCHGt00x5zMSOpCPoomQ3Sg="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/liggitt/tabwriter"]
    version = "v0.0.0-20181228230101-89fcab3d43de"
    hash = "sha256-b6pLitORwgfGpOHpe45ykj00P17utbDv8bv6MCVoCBM="
  [mod."github.com/mailgun/mailgun-go/v3"]
    version = "v3.6.4"
    hash = "sha256-//QGyCNr5csr8DQV27DK0PuCCSFZCgIGnCiuRmwZPtI="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.6"
    hash = "sha256-lObieB06Ep7xL3Bbc1sxWpAeqH9VH2LXsPIc9uueuXs="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.2"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/moby/spdystream"]
    version = "v0.2.0"
    hash = "sha256-Feme5UoWuBCvnLPKw1ozKkF3SM7PAjjPFQZ3TJhghR0="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/monochromegane/go-gitignore"]
    version = "v0.0.0-20200626010858-205db1a8cc00"
    hash = "sha256-j1Mgb2TUUIiBcXB+slOkjtvcjmqSMEsG5RZYE7vGXOU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.8"
    hash = "sha256-JP3RZVZLFhaBZ2VdF/fbyMPMLqrPZDjP98f1ey2OePo="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.16.5"
    hash = "sha256-Q3CKWQyIJKOiX9cs4t5Nz4pYxj6CT3AWnMXRNiM71GQ="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.7.0"
    hash = "sha256-BKqQKCsPA73FaQwYpAY+QsWFHIncrG5jgRhC2IiNmCk="
  [mod."github.com/onsi/gomega"]
    version = "v1.24.2"
    hash = "sha256-iascSzzBT1Uv/XybezSblIwwrq78BU4a9BVB5MvK6MM="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/openshift/api"]
    version = "v3.9.0+incompatible"
    hash = "sha256-rawzDdF7xnQYXwKWYCMCLXrtQ8MojTWW2mkpwrzgCeU="
  [mod."github.com/peterbourgon/diskv"]
    version = "v2.0.1+incompatible"
    hash = "sha256-K4mEVjH0eyxyYHQRxdbmgJT0AJrfucUwGB2BplRRt9c="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.8.0"
    hash = "sha256-hgrilokQsXCOCCvwgOSfuErxoFAQpXM/+zNJKcMVHyM="
  [mod."github.com/spf13/cobra"]
    version = "v1.6.1"
    hash = "sha256-80B5HcYdFisz6QLYkTyka7f9Dr6AfcVyPwp3QChoXwU="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.0"
    hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="
  [mod."github.com/xlab/treeprint"]
    version = "v1.1.0"
    hash = "sha256-nq0RNV7zpnLmAy9TvH4FJrk2z2vxYZZs3PCZMMxjUJw="
  [mod."go.starlark.net"]
    version = "v0.0.0-20200306205701-8dd3e2ee1dd5"
    hash = "sha256-O104Aj4+yPVFMJF2gG3hoRGbc5tbNS3kj8JQOuj7MoQ="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."go.uber.org/zap"]
    version = "v1.24.0"
    hash = "sha256-yLzjFbMWnc5b033gcPLGP0KY1xWPJ3sjnUG/RndmC3o="
  [mod."golang.org/x/crypto"]
    version = "v0.1.0"
    hash = "sha256-0oZWBSiW5Pd/2a1p2beuoelDe0CpfXZhrg/qPduJlYs="
  [mod."golang.org/x/mod"]
    version = "v0.7.0"
    hash = "sha256-ur4ld/ZtS6fnjLpHje0i00buolCTxVDH/HBJPfTj1Yc="
  [mod."golang.org/x/net"]
    version = "v0.7.0"
    hash = "sha256-LgZYZRwtMqm+soNh+esxDSeRuIDxRGb9OEfYaFJHCDI="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20220223155221-ee480838109b"
    hash = "sha256-nmUbDsBh29MUKFU89+wqlksNgz6suQrSB2Ax5VjkE3Q="
  [mod."golang.org/x/sys"]
    version = "v0.5.0"
    hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="
  [mod."golang.org/x/term"]
    version = "v0.5.0"
    hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="
  [mod."golang.org/x/text"]
    version = "v0.7.0"
    hash = "sha256-ydgUqX+t5Qke16C6d3FP/06U/N1n+rUKpLRFj4KXjwk="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."gomodules.xyz/jsonpatch/v2"]
    version = "v2.2.0"
    hash = "sha256-PhyOjXzIs3M0HXoVTWXQnqXL4S0s/DlE0IfX6A+oBJc="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/alexcesaro/quotedprintable.v3"]
    version = "v3.0.0-20150716171945-2caba252f4dc"
    hash = "sha256-6cgI1fteSkqNYkNeReaHz0El7hbomNiRyueg44BHI7o="
  [mod."gopkg.in/gomail.v2"]
    version = "v2.0.0-20160411212932-81ebce5c23df"
    hash = "sha256-rCKRESTIHR6dkn4HEx6ZlxHfqLTmJvIAtjQFXXaevn0="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/api"]
    version = "v0.26.2"
    hash = "sha256-Vx3CBHPMbyNx+ead5eeNyCj0mRvmtq6IprDIGi+gQO0="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.26.1"
    hash = "sha256-1wRbzA8WE4OhvIrNlS8xsJo0tepJ8NC2lWMFhuPSe98="
  [mod."k8s.io/apimachinery"]
    version = "v0.26.2"
    hash = "sha256-yWnEgX5MW+geftt/uH5Fp+0lRiZ1uIsQDs25UBf84z4="
  [mod."k8s.io/cli-runtime"]
    version = "v0.26.2"
    hash = "sha256-yuk2cygHdex7N41vXzGi7eSzJHqM7qfjof6mzFw4BjM="
  [mod."k8s.io/client-go"]
    version = "v0.26.2"
    hash = "sha256-pvOAY2Ilw1XcHnL+yOA3VDuPB5Sm69NSDdnSk9/EqQE="
  [mod."k8s.io/component-base"]
    version = "v0.26.1"
    hash = "sha256-IhSolWORDKtxW7rDHhduWm+suKrESHT1bQf/tjtmXto="
  [mod."k8s.io/klog/v2"]
    version = "v2.80.1"
    hash = "sha256-2x5xerTWGlkutsiqOsIyvTG7k0NSfcZqhgDLSmtbxGU="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20221012153701-172d655c2280"
    hash = "sha256-WoBpg3hcwOlGmH8CVQp9f8DS9IA5sUJEbMd4p1R35bc="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20221128185143-99ec85e7a448"
    hash = "sha256-pQXV7Vjq1zL7tLcl3jdj//lPzfzPShMJDdhnHewe5Fg="
  [mod."sigs.k8s.io/controller-runtime"]
    version = "v0.14.5"
    hash = "sha256-Di24DK8uBpSz1C9sY3quM57JKUIm8BiiX/HIB5ERg5A="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20220713155537-f223a00ba0e2"
    hash = "sha256-hWhSoc0Y7YbWfUbesf0tOgEPK61F/tNQo2zN6RcYgro="
  [mod."sigs.k8s.io/kustomize/api"]
    version = "v0.12.1"
    hash = "sha256-dzyBhQn1GA5WjQILesrStKoGFh8BIZ/kxE+AAyTGvs0="
  [mod."sigs.k8s.io/kustomize/kyaml"]
    version = "v0.13.9"
    hash = "sha256-7dyUt/+ys0qcMEX0OMGY35YOIcy0/gUMyje5gtoC7AI="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
